" Colemak navigation shared by Vim, Neovim, and VSCodeVim.
nnoremap n j
nnoremap e k
nnoremap N }
nnoremap E {
nnoremap <C-n> <C-d>
nnoremap <C-e> <C-u>

" Repeat the last search without reclaiming another single-letter command.
nnoremap ]n n
nnoremap [n N
